INSERT INTO person (first_name, last_name, enabled, gender, address) VALUES
('Nicky', 'Kirkhouse', true, 'Female', '668 Pennsylvania Court'),
('Mort', 'Easson', false, 'Male', '75362 Mesta Alley'),
('Raeann', 'Fydoe', true, 'Female', '153 Lotheville Alley'),
('Nesta', 'Edinborough', false, 'Female', '64 Acker Street'),
('Cord', 'Lomond', false, 'Male', '261 Mosinee Hill'),
('Trudey', 'Biffin', false, 'Female', '1845 Calypso Parkway'),
('Janenna', 'Shepherdson', false, 'Female', '85 Becker Junction'),
('Rhody', 'Clurow', false, 'Female', '78 Rowland Circle'),
('Grace', 'Corness', false, 'Female', '93129 Shoshone Terrace'),
('Winthrop', 'Raithby', true, 'Male', '847 Vidon Hill'),
('Zita', 'Hugonneau', true, 'Female', '873 Riverside Street'),
('Vincent', 'Fisk', true, 'Male', '7086 Summit Circle'),
('Sherill', 'Ling', true, 'Female', '68 Mifflin Center'),
('Beatrisa', 'Bairnsfather', true, 'Female', '502 Oak Valley Parkway'),
('Boony', 'Yegorshin', true, 'Male', '68 Waubesa Trail'),
('Barn', 'Quig', false, 'Male', '00898 Larry Avenue'),
('Charlie', 'Joincey', false, 'Male', '0 Butternut Road'),
('Rouvin', 'Vuittet', true, 'Male', '673 Sunbrook Pass'),
('Ric', 'Woodeson', true, 'Male', '80409 Elka Park'),
('Jermayne', 'Peetermann', false, 'Male', '95 Barnett Junction'),
('Carl', 'Renzini', true, 'Male', '59228 Welch Junction'),
('Belvia', 'Rathmell', true, 'Female', '3 Claremont Point'),
('Findley', 'Cardew', false, 'Male', '1 Farragut Place'),
('Sharity', 'Wattinham', false, 'Female', '0 Grasskamp Parkway'),
('Seumas', 'Dommett', true, 'Male', '20 Karstens Plaza'),
('Edward', 'Bengochea', true, 'Male', '2471 Union Drive'),
('Starlin', 'Balsdone', true, 'Female', '912 Hazelcrest Trail'),
('Auroora', 'Pakeman', true, 'Female', '8 Service Junction'),
('Leola', 'Murfin', true, 'Female', '47561 Miller Pass'),
('Nessi', 'Danzig', true, 'Female', '76163 Dottie Circle'),
('Benji', 'Eacott', true, 'Male', '840 Harper Junction'),
('Caty', 'Nudds', false, 'Female', '29321 Golf Course Hill'),
('Rafaello', 'Siddens', true, 'Male', '78 Lawn Avenue'),
('Olympe', 'Van den Broek', false, 'Female', '04306 Lerdahl Court'),
('Cthrine', 'Broddle', true, 'Female', '531 Shopko Street'),
('Meta', 'Ivey', true, 'Female', '5 Donald Park'),
('Ryon', 'Bengle', true, 'Male', '1240 Farmco Avenue'),
('Corrie', 'Ginity', false, 'Female', '953 Summit Plaza'),
('Frankie', 'Larby', true, 'Male', '10 Swallow Road'),
('Stinky', 'Nicholl', true, 'Male', '68825 Banding Circle'),
('Luigi', 'Luney', true, 'Male', '0016 Amoth Parkway'),
('Zollie', 'Aggs', false, 'Male', '501 Melvin Park'),
('Ruth', 'Greenstead', true, 'Female', '3421 Menomonie Avenue'),
('Timofei', 'Sabine', true, 'Male', '4212 Sutherland Lane'),
('Jessalyn', 'Spare', false, 'Female', '19 Moose Circle'),
('Skyler', 'Arnull', true, 'Male', '6 Gateway Parkway'),
('Sherm', 'Hogbourne', true, 'Male', '728 Manufacturers Trail'),
('Dayle', 'Hrachovec', true, 'Female', '9823 Rockefeller Circle'),
('Paxon', 'Hedon', false, 'Male', '05416 Novick Point'),
('Virgilio', 'Humphrey', false, 'Male', '69 Stuart Hill'),
('Marian', 'Tomasutti', false, 'Female', '1429 Morrow Road'),
('Sheba', 'Eastmond', false, 'Female', '178 Fisk Avenue'),
('Anna-maria', 'Crutchley', false, 'Female', '07486 Green Ridge Drive'),
('Remy', 'Burr', false, 'Male', '4600 Tomscot Lane'),
('Alejoa', 'Simms', true, 'Female', '9 Miller Place'),
('Eldridge', 'Pitcaithley', true, 'Male', '14 Gateway Street'),
('Ezechiel', 'Nurrish', true, 'Male', '7173 Graceland Point'),
('Dina', 'Splevins', false, 'Female', '1 Wayridge Pass'),
('Petey', 'Scullard', true, 'Male', '3 Randy Junction'),
('Montague', 'Bartosch', false, 'Male', '92952 Eggendart Place'),
('Morna', 'Blatcher', false, 'Female', '84 Anthes Hill'),
('Lyndsay', 'Smeed', true, 'Female', '414 Muir Plaza'),
('Tomasine', 'Lydden', false, 'Female', '327 Crescent Oaks Hill'),
('Inger', 'MacGiany', false, 'Female', '69 Scott Pass'),
('Jordanna', 'Belam', true, 'Female', '139 Gateway Junction'),
('Lelah', 'Blowin', true, 'Female', '90 Scott Road'),
('Valentine', 'Olner', true, 'Male', '4 Portage Street'),
('Antone', 'Keaves', true, 'Male', '97005 Huxley Circle'),
('Georgianna', 'Mevius', false, 'Female', '183 Spohn Drive'),
('Hale', 'Albany', true, 'Male', '18 Schiller Parkway'),
('Zackariah', 'Beddoes', false, 'Male', '6 Rieder Point'),
('Haskell', 'Faulks', false, 'Male', '89 Goodland Parkway'),
('Alvira', 'Yakunin', true, 'Female', '47 Grover Crossing'),
('Harrietta', 'Cathery', true, 'Female', '996 Talisman Road'),
('Sidonia', 'Towhey', true, 'Female', '0868 Linden Parkway'),
('Deb', 'McGoun', true, 'Female', '0 Scoville Street'),
('Meriel', 'Husson', false, 'Female', '6884 Lighthouse Bay Point'),
('Celestyna', 'MacDonnell', true, 'Female', '09729 Mccormick Place'),
('Guinevere', 'Petch', true, 'Female', '5 Badeau Parkway'),
('Casey', 'Brewitt', true, 'Male', '2871 Pearson Point'),
('Juliane', 'Lywood', true, 'Female', '9480 Warrior Park'),
('Alyss', 'Addionizio', false, 'Female', '728 Fair Oaks Hill'),
('Nicki', 'Hobson', false, 'Female', '14 Scott Junction'),
('Bennie', 'Rodenburg', true, 'Male', '683 Bunker Hill'),
('Emalee', 'Dunlop', true, 'Female', '4615 Bashford Trail'),
('Ede', 'Cartman', true, 'Female', '50810 Vera Junction'),
('Vikky', 'Hark', true, 'Female', '05 Mendota Lane'),
('Hartwell', 'Fitzroy', true, 'Male', '58816 Reinke Street'),
('Jeanine', 'Gossan', true, 'Female', '3 Delladonna Hill'),
('Jamima', 'Plews', false, 'Female', '01744 Riverside Drive'),
('Madlin', 'Sherrington', true, 'Female', '1 Fairfield Drive'),
('Lelah', 'Riccardelli', false, 'Female', '36592 Becker Lane'),
('Philippine', 'Meaddowcroft', true, 'Female', '3686 Dunning Place'),
('Pru', 'Riolfi', true, 'Female', '64 Johnson Alley'),
('Whitman', 'Yule', true, 'Male', '7254 Sauthoff Lane'),
('Pablo', 'Grinham', true, 'Male', '197 Kipling Parkway'),
('Eddie', 'McClelland', true, 'Male', '981 Gerald Pass'),
('Winona', 'Airey', true, 'Female', '93 Lyons Crossing'),
('Yardley', 'Stailey', false, 'Male', '83648 Chive Parkway'),
('Ogdan', 'Warstall', false, 'Male', '8938 Hanover Way'),
('Kerk', 'Pallas', true, 'Male', '19234 Heffernan Place'),
('Lyndsey', 'Marsden', true, 'Female', '25 Troy Point'),
('Cathlene', 'Cheese', true, 'Female', '8376 Grover Park'),
('Ardelle', 'Nealon', true, 'Female', '9 Burrows Alley'),
('Loria', 'Barthelme', false, 'Female', '96 Reindahl Crossing'),
('Griffy', 'Darnbrough', false, 'Male', '38 Golden Leaf Drive'),
('Donny', 'Aggleton', false, 'Male', '0 Norway Maple Road'),
('Sianna', 'Forsdick', false, 'Female', '73 Anthes Road'),
('Tymon', 'Krishtopaittis', true, 'Male', '2 Red Cloud Street'),
('Caty', 'Fossey', false, 'Female', '06666 Starling Avenue'),
('Konstantin', 'Sworder', true, 'Male', '76007 Badeau Place'),
('Ambrose', 'Shervington', true, 'Male', '1798 New Castle Place'),
('Gerhardt', 'Pinnock', false, 'Male', '07 Warner Place'),
('Otho', 'Trollope', true, 'Male', '89421 Merrick Road'),
('Clayborne', 'Drillingcourt', false, 'Male', '5 Main Lane'),
('Javier', 'Andriolli', true, 'Male', '725 Anthes Point'),
('Sallee', 'Andrini', true, 'Female', '186 Debra Lane'),
('Sarina', 'Huckerbe', true, 'Female', '04 Loomis Parkway'),
('Allys', 'Danne', true, 'Female', '32 Mcbride Pass'),
('Torey', 'Shanklin', true, 'Male', '16 Caliangt Terrace'),
('Gusti', 'Gutch', false, 'Female', '1981 Spaight Pass'),
('Adah', 'Cumberledge', true, 'Female', '60 Mayer Street'),
('Devlen', 'Sydenham', true, 'Male', '91 Barby Pass'),
('Jacquenette', 'Muldowney', true, 'Female', '11527 Hudson');